services:
  database:
    container_name: "postgres-dev"
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apicursos
    ports:
      - "5432:5432"
